name: Release
on:
  workflow_dispatch:
    inputs:
      releaseName:
        description: 'Name of the release'
        type: string
        required: true

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build sev-snp
        run: cargo build --release
        working-directory: ./kernel-hasher
      - name: Create release
        run: gh release create ${{ inputs.releaseName }} --title ${{ inputs.releaseName }} ./kernel-hasher/target/release/kernel-hasher
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
